common: &common
  secret_key_base: 'f0b774b4d06f7ea3357dec260cd6231367009d35525b3c437b27e299d52599bebd4eb1cd83fc3f69ff0d46a0510e5e4ba3bffd26b503b7713100f6083fc4baba'

  smtp:
    user_name: <%= ENV['SMTP_USER_NAME'] || 'owen' %>
    password: <%= ENV['SMTP_PASSWORD'] || 'this_is_not_the_password' %>
    address: <%= ENV['SMTP_ADDRESS'] || 'newton.cx' %>
    domain: <%= ENV['SMTP_DOMAIN'] || 'newton.cx' %>
    port: <%= (ENV['SMTP_PORT'] || 465).to_i %>

test:
  <<: *common

development:
  <<: *common

# Do not keep production secrets in the repository, read values from the environment.
production:
  <<: *common

  # Specificly do not use value in common as fallback
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
